#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := YuexIotSolution

SRCDIRS += components/wifi/smart_config components/general/led components/general/led/status_led components\wifi\wifi_conn components\general\button components\general\button\button
include $(IDF_PATH)/make/project.mk

